### ISSUE TITLE
cannot archive. Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by kumangdeal** [crownstone/bluenet-lib-ios#1]
Hi, i tried to archive and failed.

here's what i got ?

`Undefined symbols for architecture armv7:
  "Swift.UnsafeMutableBufferPointer.(subscript.materializeForSet : (Swift.Int) -> A).(closure #1)", referenced from:
      function signature specialization <Arg[2] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> with Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.RandomAccessCollection in Swift> of Swift._siftDown <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, index : A.Index, subRange : Swift.Range<A.Index>, by : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> () in PABeaconMonitor.o
      function signature specialization <Arg[1] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> with Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.RandomAccessCollection in Swift> of Swift._heapSort <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, subRange : Swift.Range<A.Index>, by : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> () in PABeaconMonitor.o
      function signature specialization <Arg[1] = Exploded> of generic specialization <Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> with Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.MutableCollection in Swift and Swift.UnsafeMutableBufferPointer<BluenetLibIOS.iBeaconPacket> : Swift.RandomAccessCollection in Swift> of Swift._partition <A where A: Swift.MutableCollection, A: Swift.RandomAccessCollection> (inout A, subRange : Swift.Range<A.Index>, by : inout (A.Iterator.Element, A.Iterator.Element) -> Swift.Bool) -> A.Index in PABeaconMonitor.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

any idea why ? thanks!

**Comment by AlexDM0** [comment]
Hi,

Did you use carthage to add bluenetLibIOS to your app? BluenetLibIOS is not made to be archived independently. Did you add the run script phase from carthage?

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

What version of xcode are you using together with which version of the lib?

Regards

**Comment by kumangdeal** [comment]
the issue is from my code. sorry for bothering. thanks!
