### ISSUE TITLE
Tracking does not last forever.

### ISSUE THREAD

**Issue by Mergon** [crownstone/bluenet-lib-ios#2]
After many tests and revisions, we have found that, given a smartphone carried inside a building over multiple hours, set to track the region of all the beacons in that building, not running in the foreground, eventually location updates will cease to come until the app is woken back up. Typically this takes something in the realm of 30 minutes.

I've eventually found that Apple states that the location updates background mode doesn't actually allow ranging to run indefinitely - "Enabling this mode does not prevent the system from suspending the app, but it does tell the system that it should wake up the app whenever there is new location data to deliver." So even if tracking is left on, even if ranging is left on, eventually the process is killed until another kind of event triggers the location services.

Is this correct, or does this conflict with your findings? It would seem an additional source of triggers (such as the pedometer) will be needed to keep ranging live through a day.

**Comment by AlexDM0** [comment]
We've not tested it for long periods of time yet. This is something that we will have to look at.

**Comment by AlexDM0** [comment]
In our latest testing with the new firmware on the Crownstones, the tracking does last essentially for ever. The issue was the following of the ibeacon spec in the beacons.

Cheers
